name: Build All


on: [workflow_dispatch]

jobs:

  build-arm6:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: build backend plugin
        run: make build-backend-cross-linux-arm6
      - name: Upload dist folder
        uses: actions/upload-artifact@v2
        with:
          name: plugin-arm6
          path: ./dist/

  build-arm7:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: build backend plugin
        run: make build-backend-cross-linux-arm7
      - name: Upload dist folder
        uses: actions/upload-artifact@v2
        with:
          name: plugin-arm7
          path: ./dist/

  build-arm64:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: build backend plugin
        run: make build-backend-cross-linux-arm64
      - name: Upload dist folder
        uses: actions/upload-artifact@v2
        with:
          name: plugin-arm64
          path: ./dist/

  build-linux64:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Install go dependencies
        run: make install-go
      - name: build linux version
        run: make build-backend
      - name: Upload linux binary
        uses: actions/upload-artifact@v2
        with:
          name: plugin-linux64
          path: ./dist/

  build-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Install go dependencies
        run: make install-go
      - name: build windows version
        run: make build-backend
      - name: Upload windows binary
        uses: actions/upload-artifact@v2
        with:
          name: plugin-windows64
          path: ./dist/

